# Generated by Django 4.2.16 on 2024-10-05 10:00

from django.db import migrations, models
import userapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='mylink',
            name='hash',
            field=models.CharField(default=userapp.utils.generate_hash, max_length=50, unique=True),
        ),
    ]
