# Generated by Django 4.2.16 on 2024-10-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_people_alter_mylink_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=6, unique=True)),
                ('short_url', models.URLField()),
                ('qr_code_url', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('visit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.people')),
            ],
        ),
        migrations.DeleteModel(
            name='MyLink',
        ),
    ]
