# Generated by Django 4.2.16 on 2024-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_short_url_delete_mylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='Number_of_shorterned_links',
            field=models.IntegerField(default=0),
        ),
    ]
