# Generated by Django 4.2.16 on 2024-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_short_url_number_of_shorterned_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='Number_of_shorterned_links',
        ),
        migrations.AddField(
            model_name='people',
            name='Number_of_shorterned_links',
            field=models.IntegerField(default=0),
        ),
    ]
